/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Ants
 */
public class RecursionGUI extends javax.swing.JFrame
{

    private final Recursion recursion;

    /**
     * Creates new form RecursionGUI
     */
    public RecursionGUI()
    {
        initComponents();
        this.recursion = new Recursion();
    }

    private void display(String x)
    {
        System.out.println(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSeparator1 = new javax.swing.JSeparator();
        exponentButton = new javax.swing.JButton();
        gcdButton = new javax.swing.JButton();
        factorialButton = new javax.swing.JButton();
        powerButton = new javax.swing.JButton();
        applicationLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        closeButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        palindromeButton = new javax.swing.JButton();
        applicationLabel2 = new javax.swing.JLabel();
        applicationLabel3 = new javax.swing.JLabel();
        primeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECURSION APPLICATION");

        exponentButton.setText("EXPONENT");
        exponentButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exponentButtonActionPerformed(evt);
            }
        });

        gcdButton.setText("GCD");
        gcdButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gcdButtonActionPerformed(evt);
            }
        });

        factorialButton.setText("FACT");
        factorialButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                factorialButtonActionPerformed(evt);
            }
        });

        powerButton.setText("POWER");
        powerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                powerButtonActionPerformed(evt);
            }
        });

        applicationLabel1.setForeground(new java.awt.Color(255, 0, 0));
        applicationLabel1.setText("APPLICATION ONE");

        closeButton.setText("CLOSE");
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        palindromeButton.setText("PALINDROME CHECK");
        palindromeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                palindromeButtonActionPerformed(evt);
            }
        });

        applicationLabel2.setForeground(new java.awt.Color(0, 153, 0));
        applicationLabel2.setText("APPLICATION TWO");

        applicationLabel3.setForeground(new java.awt.Color(0, 153, 153));
        applicationLabel3.setText("APPLICATION THREE");

        primeButton.setText("PRIME NUMBER");
        primeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                primeButtonActionPerformed(evt);
            }
        });

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exponentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gcdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(factorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(palindromeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(primeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(applicationLabel1)
                            .addComponent(applicationLabel2)
                            .addComponent(applicationLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(applicationLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powerButton)
                    .addComponent(factorialButton)
                    .addComponent(gcdButton)
                    .addComponent(exponentButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(applicationLabel2)
                .addGap(11, 11, 11)
                .addComponent(palindromeButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applicationLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(primeButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_powerButtonActionPerformed
    {//GEN-HEADEREND:event_powerButtonActionPerformed

        output.setText("");

        String x = JOptionPane.showInputDialog("Enter Number");
        int number = Integer.parseInt(x);
        int con = 1;

        int result = this.recursion.place(number, con);

        System.out.println(result + "\n");

        output.setText("" + result);

    }//GEN-LAST:event_powerButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void exponentButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exponentButtonActionPerformed
    {//GEN-HEADEREND:event_exponentButtonActionPerformed

        output.setText("");

        String x = JOptionPane.showInputDialog("Enter Base Number");
        int base = Integer.parseInt(x);

        String y = JOptionPane.showInputDialog("Enter Exponent Number");
        int exponent = Integer.parseInt(y);

        int result = this.recursion.power(base, exponent);

        output.setText("" + result);

    }//GEN-LAST:event_exponentButtonActionPerformed

    private void gcdButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gcdButtonActionPerformed
    {//GEN-HEADEREND:event_gcdButtonActionPerformed

        output.setText("");

        String x = JOptionPane.showInputDialog("Enter Value ONE Number");
        int one = Integer.parseInt(x);

        String y = JOptionPane.showInputDialog("Enter Value TWO Number");
        int two = Integer.parseInt(y);

        int result = this.recursion.gcd(one, two);

        output.setText("" + result);

    }//GEN-LAST:event_gcdButtonActionPerformed

    private void factorialButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_factorialButtonActionPerformed
    {//GEN-HEADEREND:event_factorialButtonActionPerformed

        output.setText("");

        String x = JOptionPane.showInputDialog("Enter Number");
        int number = Integer.parseInt(x);

        int result = this.recursion.factorial(number);

        output.setText("" + result);

    }//GEN-LAST:event_factorialButtonActionPerformed

    private void primeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_primeButtonActionPerformed
    {//GEN-HEADEREND:event_primeButtonActionPerformed

        output.setText("");

        String x = JOptionPane.showInputDialog("Enter Number");
        int number = Integer.parseInt(x);

        int result = this.recursion.prime(number, number / 2);

        if (result == 1)
        {
            output.setText(number + " IS a Prime Number\n");
            // System.out.println(number + " IS a Prime Number\n");
        } else
        {
            output.setText(number + " Is NOT a Prime Number\n");
            //System.out.println(number + " IS NOT a Prime Number\n");
        }

    }//GEN-LAST:event_primeButtonActionPerformed

    private void palindromeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_palindromeButtonActionPerformed
    {//GEN-HEADEREND:event_palindromeButtonActionPerformed

        output.setText("");

        String input = JOptionPane.showInputDialog("Enter Word");
        char[] word = input.toCharArray();

        boolean result = this.recursion.checkP1(word);

        if (result == true)
        {
            output.setText(result + ": It IS a Palindrome!!\n");
        } else
        {
            output.setText(result + ": Sorry, NOT a Palindrome..\n");
        }

        //System.out.println(result + "\n");

    }//GEN-LAST:event_palindromeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RecursionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicationLabel1;
    private javax.swing.JLabel applicationLabel2;
    private javax.swing.JLabel applicationLabel3;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton exponentButton;
    private javax.swing.JButton factorialButton;
    private javax.swing.JButton gcdButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea output;
    private javax.swing.JButton palindromeButton;
    private javax.swing.JButton powerButton;
    private javax.swing.JButton primeButton;
    // End of variables declaration//GEN-END:variables
}
